BEGIN;

CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  username VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(256) NOT NULL,
  active BOOLEAN NOT NULL,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL
);

GRANT INSERT, UPDATE, SELECT, DELETE ON users TO rsapi;
GRANT USAGE, SELECT, UPDATE ON users_id_seq TO rsapi;

COMMIT;
